### ISSUE TITLE
Sources are pointing at branches which may be updated

### ISSUE THREAD

**Issue by Taneb** [streams-r-us/ajantv2-nix#2]
This puts us in danger of not matching the upstream source, so things will continue to build locally (because we have things cached in our nix store) but if we garbage collect or try to build on a new computer, the build will report an incorrect hash.

We should instead either pick a specific commit or a release tag, which is unlikely to change, for each of the two sources.

**Comment by Taneb** [comment]
Actually I wonder if we could do them as non-flake flake inputs. I'm not quite sure how those work...

**Comment by wlcx** [comment]
How about this https://github.com/streams-r-us/ajantv2-nix/commit/9e1beef1c8b00e60f34f53de153273a91dd1128f

**Comment by Taneb** [comment]
Looks decent but I can't test it out right now

**Comment by Taneb** [comment]
Looks decent but I can't test it out right now
